### ISSUE TITLE
Job scheduled to very low repeat

### ISSUE THREAD

**Issue by atomaka** [sudaraka94/opencollective-plugin#3]
Currently, the jobs this plugin runs are set to run every `50.seconds`.  Similar plugins tend to run their background processes once every day.  Is there a reason you've set such a low time or is this strictly for testing purposes?

**Comment by sudaraka94** [comment]
It was for testing purposes @atomaka . Will reduce them to a day .It will be sufficient

**Comment by atomaka** [comment]
One day seems reasonable and in line with similar plugins. I think we'll run into an architecture at that point. I'll submit the problem and proposed solution in about 9 hours.
